admin_home:
   pattern: /
   defaults: { _controller: FfblAdminBundle:Default:index }

admin_player:
   pattern: /player
   defaults: {_controller: FfblAdminBundle:Player:index }

admin_user:
   pattern: /user
   defaults: {_controller: FfblAdminBundle:User:index }

tool_user_admintool:
    pattern: /user/admintool
    defaults: { _controller: FfblAdminBundle:User:admintool }

ajax_user_admintool:
    pattern: /user/ajax	defaults
    defaults: { _controller: FfblAdminBundle:User:adminajax }
    requirements:
        _method: POST