ffbl_admin:
    resource: "@FfblAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

ffbl_main:
    resource: "@FfblMainBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /logout