home:
     pattern: /
     defaults: { _controller: FfblMainBundle:Default:index }

login:
    pattern: /login
    defaults: {_controller: FfblMainBundle:Security:login }
login_check:
    pattern: /login_check

unauthorized:
    pattern: /unauthorized
    defaults: { _controller: FfblMainBundle:Security:unauthorized }